# Generated by Django 5.2.16 on 2026-07-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("score_total", models.FloatField()),
                ("answers", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Soumission de diagnostic",
                "verbose_name_plural": "Soumissions de diagnostic",
                "ordering": ["-timestamp"],
            },
        ),
    ]
